-- 최초 Compose DB 스키마. 적용 후에는 수정하지 않고 V2 이상으로 변경한다.
CREATE TABLE source (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    base_url VARCHAR(500) NOT NULL,
    code VARCHAR(50),
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_source_name UNIQUE (name),
    CONSTRAINT uk_source_code UNIQUE (code)
);

CREATE TABLE deal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id BIGINT NOT NULL,
    external_id VARCHAR(200) NOT NULL,
    title VARCHAR(300) NOT NULL,
    description TEXT,
    price BIGINT,
    original_price BIGINT,
    discount_rate INTEGER,
    currency VARCHAR(8) NOT NULL DEFAULT 'KRW',
    category VARCHAR(50),
    shop_name VARCHAR(100),
    comment_count INTEGER,
    thumbnail_url VARCHAR(1000),
    original_url VARCHAR(1000) NOT NULL,
    product_url VARCHAR(2000),
    title_norm_hash VARCHAR(64),
    group_id BIGINT,
    status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
    posted_at TIMESTAMP WITH TIME ZONE NOT NULL,
    collected_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_deals_source FOREIGN KEY (source_id) REFERENCES source (id),
    CONSTRAINT uk_deal_source_external_id UNIQUE (source_id, external_id),
    CONSTRAINT uk_deal_group_source UNIQUE (group_id, source_id),
    CONSTRAINT ck_deal_status CHECK (status IN ('ACTIVE', 'EXPIRED', 'SOLD_OUT'))
);

CREATE TABLE deal_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    representative_deal_id BIGINT NOT NULL UNIQUE,
    canonical_title VARCHAR(300) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_deal_group_representative_deal FOREIGN KEY (representative_deal_id) REFERENCES deal (id)
);

-- 순환 참조: 원본 Deal을 먼저 저장하고 그룹을 만든 뒤 Deal을 연결한다.
ALTER TABLE deal ADD CONSTRAINT fk_deal_group FOREIGN KEY (group_id) REFERENCES deal_group (id);

CREATE TABLE source_visibility (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    source_id BIGINT NOT NULL,
    visible BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_source_visibility_source FOREIGN KEY (source_id) REFERENCES source (id),
    CONSTRAINT uk_source_visibility_user_source UNIQUE (user_id, source_id)
);

CREATE TABLE keyword (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    keyword VARCHAR(50) NOT NULL,
    type VARCHAR(10) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_keyword_user_keyword_type UNIQUE (user_id, keyword, type),
    CONSTRAINT ck_keyword_type CHECK (type IN ('INTEREST', 'EXCLUDE'))
);

CREATE INDEX idx_deal_source_id ON deal (source_id);
CREATE INDEX idx_deal_posted_at ON deal (posted_at DESC);
CREATE INDEX idx_deal_discount_rate ON deal (discount_rate DESC);
CREATE INDEX idx_deal_status ON deal (status);
CREATE INDEX idx_deal_title_norm_hash ON deal (title_norm_hash);
CREATE INDEX idx_deal_group_id ON deal (group_id);
CREATE INDEX idx_source_visibility_user_id ON source_visibility (user_id);
CREATE INDEX idx_keyword_user_type ON keyword (user_id, type);
