import type {
  AISummary,
  BestItem,
  CategoryId,
  Deal,
  KeywordTag,
  ShopCount,
  Source,
} from "./types";

export const SOURCES: Source[] = [
  { id: "ruliweb", name: "루리웹", enabled: true },
  { id: "fmkorea", name: "펨코", enabled: true },
  { id: "quasarzone", name: "퀘이사존", enabled: true },
  { id: "reddit", name: "Reddit", enabled: true },
  { id: "slickdeals", name: "Slickdeals", enabled: true },
];

export const SHOP_COUNTS: ShopCount[] = [
  { id: "all", name: "전체", count: 23 },
  { id: "coupang", name: "쿠팡", count: 21 },
  { id: "naver", name: "네이버", count: 18 },
  { id: "11st", name: "11번가", count: 11 },
  { id: "gmarket", name: "G마켓", count: 10 },
  { id: "ssg", name: "SSG.COM", count: 9 },
  { id: "himart", name: "하이마트", count: 6 },
  { id: "lotteon", name: "롯데온", count: 5 },
];

export const CATEGORIES: { id: CategoryId; name: string; icon: string }[] = [
  { id: "all", name: "전체", icon: "grid" },
  { id: "appliance", name: "가전", icon: "tv" },
  { id: "digital", name: "디지털", icon: "smartphone" },
  { id: "computer", name: "컴퓨터", icon: "monitor" },
  { id: "living", name: "생활/주방", icon: "utensils" },
  { id: "food", name: "식품", icon: "soup" },
  { id: "fashion", name: "패션/뷰티", icon: "shirt" },
  { id: "sports", name: "스포츠", icon: "dumbbell" },
  { id: "book", name: "도서", icon: "book" },
];

export const DEALS: Deal[] = [
  {
    id: "d-1",
    source: "ruliweb",
    sourceName: "루리웹",
    shop: "coupang",
    shopName: "쿠팡",
    category: "디지털",
    subCategory: "가전",
    title: "Apple 2024 맥북 에어 13 M3 (8GB/256GB)",
    thumbnail:
      "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=240&h=240&fit=crop",
    price: 1_089_000,
    originalPrice: 1_399_000,
    discountPercent: 21,
    currency: "KRW",
    originalUrl: "https://example.com/deal/1",
    postedAt: "3시간 전",
    voteCount: 452,
    commentCount: 32,
    isHot: true,
    freeShipping: true,
    shippingNote: "로켓배송",
  },
  {
    id: "d-2",
    source: "fmkorea",
    sourceName: "펨코",
    shop: "gmarket",
    shopName: "지마켓",
    category: "식품",
    subCategory: "육류",
    title: "곰곰 한입 떡갈비 1kg (100g X 10팩)",
    thumbnail:
      "https://images.unsplash.com/photo-1544025162-d76694265947?w=240&h=240&fit=crop",
    price: 9_900,
    originalPrice: 19_900,
    discountPercent: 50,
    currency: "KRW",
    originalUrl: "https://example.com/deal/2",
    postedAt: "1시간 전",
    voteCount: 312,
    commentCount: 16,
    isHot: true,
    freeShipping: true,
    shippingNote: "마켓",
  },
  {
    id: "d-3",
    source: "quasarzone",
    sourceName: "퀘이사존",
    shop: "auction",
    shopName: "옥션",
    category: "생활/주방",
    subCategory: "홈/가드닝",
    title: "레고 오키드 10311 (성인레고)",
    thumbnail:
      "https://images.unsplash.com/photo-1587654780291-39c9404d746b?w=240&h=240&fit=crop",
    price: 49_900,
    originalPrice: 79_900,
    discountPercent: 37,
    currency: "KRW",
    originalUrl: "https://example.com/deal/3",
    postedAt: "5시간 전",
    voteCount: 289,
    commentCount: 24,
    isHot: true,
    freeShipping: true,
    shippingNote: "옥션",
  },
  {
    id: "d-4",
    source: "reddit",
    sourceName: "Reddit",
    shop: "11st",
    shopName: "11번가",
    category: "디지털",
    subCategory: "이어폰",
    title: "Apple 에어팟 4세대 (USB-C)",
    thumbnail:
      "https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=240&h=240&fit=crop",
    price: 179_000,
    originalPrice: 219_000,
    discountPercent: 18,
    currency: "KRW",
    originalUrl: "https://example.com/deal/4",
    postedAt: "2시간 전",
    voteCount: 289,
    commentCount: 18,
    isHot: true,
    freeShipping: true,
    shippingNote: "11번가",
  },
  {
    id: "d-5",
    source: "slickdeals",
    sourceName: "Slickdeals",
    shop: "iherb",
    shopName: "iHerb",
    category: "식품",
    subCategory: "건강식품",
    title: "캘리포니아 골드 뉴트리션 오메가3 180정",
    thumbnail:
      "https://images.unsplash.com/photo-1550572017-edd951b55104?w=240&h=240&fit=crop",
    price: 11_900,
    originalPrice: 18_400,
    discountPercent: 35,
    currency: "KRW",
    originalUrl: "https://example.com/deal/5",
    postedAt: "4시간 전",
    voteCount: 198,
    commentCount: 8,
    isHot: true,
    freeShipping: false,
    shippingNote: "$40 이상 무료배송",
  },
];

export const AI_SUMMARY: AISummary = {
  body: "최근 24시간 동안 1,234개의 핫딜이 등록되었어요. 지금 가장 인기 있는 키워드는",
  highlights: ["맥북", "에어팟", "레고"],
};

export const BEST_LIST: BestItem[] = [
  { rank: 1, shopName: "네이버", title: "네이버페이 적립 4원/쇼핑라이브/12월", commentCount: 21 },
  { rank: 2, shopName: "스팀", title: "Car Mechanic Simulator 2018 (일시무료)", commentCount: 11 },
  { rank: 3, shopName: "기타", title: "모뉴먼트 밸리 3 (일시무료, 안드로이드용)", commentCount: 10 },
  { rank: 4, shopName: "스팀", title: "위해머 40000: 글라디우스 렐릭스 오브…", commentCount: 8 },
  { rank: 5, shopName: "기타", title: "다운 인 버뮤다 (일시무료)", commentCount: 7 },
  { rank: 6, shopName: "알리", title: "에디파이어 M90 역대가", commentCount: 33 },
  { rank: 7, shopName: "기타", title: "NZXT N7 B850 White 메인보드 대원씨…", commentCount: 24 },
  { rank: 8, shopName: "기타", title: "에픽: 톰레이더 1-3 리마스터", commentCount: 13 },
  { rank: 9, shopName: "지마켓", title: "메가커피 600원· 팔당 파르페 2520원…", commentCount: 5 },
  { rank: 10, shopName: "알리", title: "알리 알금날 프로모션 코드 (5/23~5/28)", commentCount: 8 },
];

export const KEYWORD_TAGS: KeywordTag[] = [
  { keyword: "맥북", count: 256 },
  { keyword: "에어팟", count: 198 },
  { keyword: "레고", count: 167 },
  { keyword: "그래픽카드", count: 145 },
  { keyword: "닌텐도", count: 134 },
  { keyword: "갤럭시", count: 112 },
  { keyword: "오메가3", count: 97 },
  { keyword: "커피", count: 86 },
  { keyword: "로봇청소기", count: 82 },
  { keyword: "모니터", count: 78 },
  { keyword: "게이밍", count: 73 },
  { keyword: "프라모델", count: 61 },
];
